### ISSUE TITLE
Mettre atoum en tant que dépendance de dev

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/libertempo-api#2]
Nous n'avons pas la garantie que le dev utilise le docker et son atoum, tout comme nous n'avons pas la main sur la version du CI et ça pourrait nous poser des problèmes car nous chercherions des problèmes là il y en a pas, suite à des versions différentes. En conséquence, je propose qu'`atoum` soit en `composer.require_dev` avec une version fixée pour s'assurer que tout le monde bosse pareil.

**Comment by wouldsmina** [comment]
#14
